### ISSUE TITLE
CodeBlock Output Error

### ISSUE THREAD

**Issue by Soptq** [penibelst/jekyll-compress-html#101]
Original html code, {{ the rest of page }} should be outside of the block
```
<div class="language-bash highlighter-rouge">
   <div class="highlight">
    <pre class="highlight"><code>
      <div class="table-responsive">
       <table class="rouge-table table">
        <tbody>
         <tr>
          <td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
</pre></td>
          <td class="rouge-code"></td>
         </tr>
        </tbody>
       </table>
      </div></code></pre>
   </div>
  </div> 
  
  {{ the rest of page }}
```

However, after compress it, {{ the rest of page }} become inside of the block, and `<pre class="highlight">`(Line 3) become `class=highlight;`
```
  <div class="language-bash highlighter-rouge">
   <div class="highlight">
     class=highlight;
    <code>
     <div class="table-responsive">
      <table class="rouge-table table">
       <tbody>
        <tr>
         <td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
</pre></td>
         <td class="rouge-code"> 

          {{ the rest of page }}

           </td>
        </tr>
       </tbody>
      </table>
     </div></code>
   </div>
  </div>

```

Which makes the whole page unusable.
Now I‘m totally having no ideas, I'll appreciate it if somebody could enlighten me a little bit.
Thanks.

**Comment by jnvsor** [comment]
Nested `pre` tags aren't supported by JCH, nor are they allowed in HTML [according to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre) - you have 2 `pre`s nested on lines 3 and 8.

**Comment by Soptq** [comment]
> Nested `pre` tags aren't supported by JCH, nor are they allowed in HTML [according to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre) - you have 2 `pre`s nested on lines 3 and 8 in your example

Thanks
