### ISSUE TITLE
Colon breaks clippings

### ISSUE THREAD

**Issue by SUPERCILEX** [penibelst/jekyll-compress-html#104]
Using `clippings: all`.

This input:

```html
<div>
  <h2>Projects</h2>
  <div>
    <img class="emoji" title=":robot:" alt=":robot:">
  </div>
</div>
```
produces this output:

```html
<div>
<h2>Projects</h2>
<div> <img class="emoji" title=":robot:" alt=":robot:">
</div>
</div>
```

However, if I remove the colons it works:

```html
<div>
  <h2>Projects</h2>
  <div>
    <img class="emoji">
  </div>
</div>
```

```html
<div><h2>Projects</h2><div> <img class="emoji"></div></div>
```

**Comment by SUPERCILEX** [comment]
Closing old issues.

**Comment by jnvsor** [comment]
I was going to work on this but it kept falling off my radar. I wanted to reopen this but I can't reproduce it anyway so I'll leave it closed

**Comment by SUPERCILEX** [comment]
Sounds good, thanks for the transparency. I've moved on to post processing my HTML, so I don't know if it's an issue or not anymore which is why I closed it.
