### ISSUE TITLE
Feature request: per page/layout configuration

### ISSUE THREAD

**Issue by dlesbre** [penibelst/jekyll-compress-html#108]
Hi ! 

I'm buiding a documentation website, and on some page I import some pre-rendered html that I really need to leave unchanged (it uses `whitespace: pre-wrap` to render some code blocks. On the other hand, its nice to compress all the other pages. It would be nice to be able to disable this (or switch to blanklines mode) on a page/layout basis. 

It should be easy to do in pure liquid. My basic fix just involved:
- adding `... or layout.compress_html == "disabled" or page.compress_html == "disabled"` to the first if (`{% if site.compress_html.ignore.envs ...`) 
- adding `... or page.compress_html == "blanklines" or layout.compress_html == "blanklines"` to `{% if site.compress_html.blanklines %}`.

This way I can just add `compress_html: disabled` or `compress_html: blanklines` to my pages/layouts at will to locally configure it. Naturally a proper implementation should consider exactly what level of customization per page/layout is desirable and achievable, but I think these two choices are a good start. 

Note that creating a layout/page that inherits from nothing is also a way to disable it per layout/page. However, its hardly practical as it involves copying the entire website layout for the page where compress_html is disabled).

**Comment by jnvsor** [comment]
I can definitely see the use for the first case of disabling it per page. I'll take a look at this
