### ISSUE TITLE
version not updated

### ISSUE THREAD

**Issue by michaelbach** [penibelst/jekyll-compress-html#109]
Thank you for maintaining this VERY useful Jekyll layout! A tiny suggestion: The lastest version, which allows page-by-page control, still contains the old version info (v3.1.0); it might be updated.

**Comment by jnvsor** [comment]
Whoops, my bad! I added a v3.2.1 tag to "Fix" this but I just swapped out the file in the 3.2.0 release rather than make a new one just to update the number :)
