### ISSUE TITLE
Remove spaces between HTML tags

### ISSUE THREAD

**Issue by leo** [penibelst/jekyll-compress-html#49]
Is there a special reason why they're existing? If not, could you please remove them? I mean, this approach could definitely save some additional bandwidth.

--

If you don't know what I'm talking about, just take a look on the source code of [this site][1].

[1]: http://leo.github.io

**Comment by kleinfreund** [comment]
Consider the following markup:

```html
<div>
text
<span>text</span>
<span>text     with     spaces</span>
</div>
```

Only `div` is a block element. The other content/`span` tags are inline. Now the way browsers read whitespace like `text     with     spaces` (see above) ignores multiple whitespace. Two spaces between words will appear as one space. New lines are also whitespace. The example above will look something like this in a browser:

> text text text with spaces

Now the new lines between the tags in the compressed HTML make sure that you don't accidentally remove _relevant_ whitespace.

Does this sound about right, @penibelst?

**Comment by penibelst** [comment]
@kleinfreund, I think @leo is asking for the `clippings` option.

@leo, please read the [documentation](http://jch.penibelst.de/) to learn how to use the `clippings` option. Make sure you understand the difference between inline and block elements, like @kleinfreund said.

**Comment by leo** [comment]
Ahh, exactly what I needed! Didn't know about that option. Thanks! :blush:

**Comment by kleinfreund** [comment]
Whoopsies :laughing:
