### ISSUE TITLE
javascript in html?

### ISSUE THREAD

**Issue by w1n78** [penibelst/jekyll-compress-html#53]
hello, i'm using your code but i run into issues with javascript in my html. i was able to solve part of the problem by moving the code into a js file. but i'm using disqus with a variable created by liquid to get the url so i have to keep the javascript in the html.

is there a way for the code to skip over <script> tags? sorry i'm a bit new. thanks.

**Comment by penibelst** [comment]
The Disqus snippet is a known troublemaker, see #8. The solution is described in the [Restrictions](http://jch.penibelst.de/#restrictions) section of the readme.
