### ISSUE TITLE
Configuration option to remove consecutive whitespace without outputting all on one line

### ISSUE THREAD

**Issue by jnvsor** [penibelst/jekyll-compress-html#57]
I would prefer my outputted source code to be somewhat easy to read. jekyll-compress-html is hard to read on one line, and jekyll itself is hard to read with dozens of lines of whitespace in between lines.

Could you please add a configuration option that would remove empty lines, but not all whitespace?

Something along the lines of:

```javascript
replace(/\n\s+\n/, "\n")
```

**Comment by kleinfreund** [comment]
You can disable compression entirely during production in your `_config.yml` with

```yaml
compress_html:
  ignore:
    envs: [local]
```

and the `JEKYLL_ENV` environment variable set to `local`.

If you want to have what you suggested in production, @penibelst will answer that.

**Comment by jnvsor** [comment]
For all intents and purposes, this disables the compression entirely - I'm looking for a middle ground where repeated newlines are removed, but not all newlines.

**Comment by jnvsor** [comment]
I've almost got a working version (Bug with pres I'm working on now) - here are the outputs

### Site output default

~~~html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Compress HTML in Jekyll</title>
  <link rel="stylesheet" href="/ui/app.css">
  <link rel="icon" href="/ui/img/favicon-1.png">
  
    <link rel="prefetch" href="https://github.com/penibelst/jekyll-compress-html">
    <link rel="prerender" href="https://github.com/penibelst/jekyll-compress-html">
  
</head>
~~~

### Site output jekyll-compress-html

~~~html
<!doctype html> <html lang="en"> <head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>Compress HTML in Jekyll</title> <link rel="stylesheet" href="/ui/app.css"> <link rel="icon" href="/ui/img/favicon-1.png"> <link rel="prefetch" href="https://github.com/penibelst/jekyll-compress-html"> <link rel="prerender" href="https://github.com/penibelst/jekyll-compress-html"> </head>
~~~

### Site output jekyll-compress-html with my patches and the config var on

~~~html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Compress HTML in Jekyll</title>
  <link rel="stylesheet" href="/ui/app.css">
  <link rel="icon" href="/ui/img/favicon-1.png">
    <link rel="prefetch" href="https://github.com/penibelst/jekyll-compress-html">
    <link rel="prerender" href="https://github.com/penibelst/jekyll-compress-html">
</head>
~~~

**Comment by penibelst** [comment]
@jnvsor Nice to see you start an implementation. Feel free to make a PR, so I can assist you.

**Comment by jnvsor** [comment]
I had to move the comment stripping before the whitespace stripping or it would leave in empty lines that had comments.

As a result the `comments/inside` test changed one byte (Only one space in a row instead of 2. Yay!) and the profile has started giving the wrong stats in `profile/whitespace`.

I intend to fix that last bug and write a test for human readable mode before submitting a PR

**Comment by kleuter** [comment]
I'd love to have it implemented. Why not?

**Comment by jnvsor** [comment]
It's been implemented since december: See blanklines

**Comment by kleuter** [comment]
**jnvsor**, thanks. But how do I enable ONLY this option?
