### ISSUE TITLE
Line above pre tags is removed

### ISSUE THREAD

**Issue by Tetr4** [penibelst/jekyll-compress-html#70]
Hi,  super praktisches layout :+1:

There seems to be an issue with lines above pre tags, when removing blanklines is enabled.
With these settings and code:
```yaml
compress_html:
  blanklines: true
```
```html
TEST
<pre>blah</pre>
```

the "TEST" line gets removed.

**Comment by Tetr4** [comment]
I did some testing, and I think the code introduced in #68 caused this issue.

**Comment by jnvsor** [comment]
Aww nuts.

**Comment by jnvsor** [comment]
@Tetr4 @penibelst I have a "Mostly done" version here: https://github.com/jnvsor/jekyll-compress-html/commit/270c3acb6e37e19c8006a6bc333dafe91bae0210

There's still a trailing newline in one of the tests and all my twiddling with booleans fixes one spot and makes it pop up in another. Liquid is whack-a-mole :hammer:

**Comment by Tetr4** [comment]
Holy moly :smile: Just tested it, looks fine to me.  
Performance and liquid code size is a problem though. I agree with [your comment](https://github.com/penibelst/jekyll-compress-html/pull/72#issuecomment-172065721) to go back to v3.0.0, too much hassle for such a small inconsistancy.

**Comment by jnvsor** [comment]
I have 2 branches with different versions. Neither of their output is correct, but they're better than what's there now (As in over 30% faster).

* [The first one](https://github.com/jnvsor/jekyll-compress-html/commit/abb1b3c26264140ea9184999b5adc79e46f9ba3d) has a tendancy to eat newlines before and after pre blocks
* [The second one](https://github.com/jnvsor/jekyll-compress-html/commit/bcccb18f119615fa1ff4f5210340e07f4517ce15) adds a tendancy to add newlines in strange places (Like the first line of the file, before the doctype. The w3c validator says nothing is wrong here but it still smells bad) It's about 5% faster than the first though.

Both of these changes only affect the aesthetics of the source code, and mostly around `<pre>` tags. The browser output should be identical to non-blanklines mode (Except javascript without semicolons which will now work where it didn't used to - yay! (Unless you have a pre tag inside your javascript or something))

Note the differences between `test/source/blanklines/*` and `test/expected/blanklines/*` in both commits.

@Tetr4 @penibelst could you guys tell me which you prefer? The first has slightly cleaner output and the second is slightly faster, though both of them are a large readability improvement on normal mode (And performance improvement on master)

**Comment by Tetr4** [comment]
I like the first one. Browser output looks fine and the code looks fine too. :+1: 
The second one adds a newline before the doctype, as you mentioned. It also puts a newline after the closing `</pre>` tag:  
This
```html
<pre>
asdf
</pre>TEST
```
becomes
```html
<pre>
asdf
</pre>
TEST
```
Though i am not sure if this is intended, but something is fishy there.

**Comment by jnvsor** [comment]
Output is fishy on the first one too. Example:

```
The next line has whitespace
    
<pre></pre>
```
Becomes
```
The next line has whitespace
    <pre></pre>
```

I just figured a 5% speed difference might be worth making a fishy output slightly fishier. If @penibelst agrees I'll submit a PR for the first one

**Comment by jnvsor** [comment]
Alrighty, went with the first draft and pushed a new release. Hope I got the release process right @penibelst
