### ISSUE TITLE
Inline Sassisified CSS getting stripped unexpectedly

### ISSUE THREAD

**Issue by jhabdas** [penibelst/jekyll-compress-html#78]
The Compress layout is a wonderful idea! But I can't use it until this issue is resolved. At a conceptual level I'd say it's similar in spirit to the caveat for using it for inline JS [as described here](http://codeheaven.io/optimizing-assets-in-jekyll-generated-gh-pages/#inline-js), though this issue is specific to inlining CSS.

## Replication

On my Jekyll site I'm inlining some styles into the head for better UX and mobile performance. The following snippet illustrates how I'm doing this:

```liquid
<style type="text/css">
  {% capture inline_styles %}
    {% include critical.scss %}
  {% endcapture %}
  {{ inline_styles | scssify }}
</style>
```

For context, the above snippet sits in a `head.html` _included_ from `header.html` from the `default.html` layout, which in turn uses `compress.html` layout `v3.0.2` under Jekyll `3.1.2`.

The contents of `critical.scss` are thus:

```sass
@charset "utf-8";
@import
  "header",
  "footer"
;
```

The Sass directory used by Jekyll is the default (i.e. `sass_dir` not overridden in Jekyll config) and the specific contents of the Sass files are not of consequence assuming they're syntactically correct.

## Actual result

When using the compress layout the Sassified and inlined contents of `header` _are not_ output to the HTML while the contents of `footer` _are_ output.

**Note:** The above holds true even when `_header.scss` contains a simple CSS selector like `header { width: 100% }`.

## Expected result

When using the compress layout the Sassified and inlined contents of `header` _are_ output in the HTML in addition to the contents of `footer`.

**Comment by jnvsor** [comment]
I'm getting exactly the same output before and after compression here. Are you sure the scssify output is correct? Can you provide the uncompressed scssify output so I can test?

**Comment by jhabdas** [comment]
I'll try and get back with a more complete example later. Meanwhile feel free to close as can't reproduce.
