### ISSUE TITLE
Remove comments from inline JS

### ISSUE THREAD

**Issue by brainbok** [penibelst/jekyll-compress-html#82]
Thanks for this nice tool.

Is there a way to remove comments from inline JS? I understand that `// comments` don't work in the inline JS and I've replaced them with `/* comments */`, but those are not stripped out in the compressed HTML output despite using `comments: all` setting.

**Comment by jnvsor** [comment]
No, it only removes HTML comments (Otherwise it would have to deal with lots of different languages)

**Comment by alexivkin** [comment]
I am sorry, what "different languages"? Is there anything else than JS that people write client side code in? If we wanted use Closure, we would have already done it. The beauty of compress is that you don't need any post processing.
