### ISSUE TITLE
Compress ruin <script> blocks

### ISSUE THREAD

**Issue by righthandabacus** [penibelst/jekyll-compress-html#83]
Simply speaking, I wish, in addition to pre blocks, we can config what other kinds of blocks (my opinion: pre, script, textarea) should be ignored in compression

**Comment by jnvsor** [comment]
This will *absolutely skyrocket* build times as we'd have to build a real full-on HTML parser in liquid (What do you do with a tag inside a tag for instance?)

To quote the docs:

> The layout is written in pure Liquid, no plugins are required.

If you don't need your site to be on GH pages or some other restricted environment, use plugins or a third party build system - see #80
