### ISSUE TITLE
Not compliant removal of <p> end tag

### ISSUE THREAD

**Issue by alexivkin** [penibelst/jekyll-compress-html#84]
All optional end tags, including `</p>` are removed unconditionally, whenever they are encountered. This is fine for most, but not some end tags. Specifically if the `</p>` is inside `<a>` (which is HTML5 compliant), it should NOT be removed, because removing it breaks the layout. Here is what [the html standard](https://html.spec.whatwg.org/multipage/syntax.html#optional-tags) says: 

A p element's end tag may be omitted if the p element is immediately followed by an address, article, aside, blockquote, details, div, dl, fieldset, figcaption, figure, footer, form, h1, h2, h3, h4, h5, h6, header, hgroup, hr, main, menu, nav, ol, p, pre, section, table, or ul element, or if there is no more content in the parent element and **the parent element is an HTML element that is not an a,** audio, del, ins, map, noscript, or video element, or an autonomous custom element.

**Comment by jnvsor** [comment]
> removed unconditionally, whenever they are encountered

You can disable this per tag with the `endings` option

**Comment by alexivkin** [comment]
I could, but that stops removing it everywhere - it 's a workaround, not a fix. As of right now compress makes non-compliant HTML code in its default configuration

**Comment by jnvsor** [comment]
I see this is related to #96 - the example made the point
