### ISSUE TITLE
Issue with <description> metatag

### ISSUE THREAD

**Issue by alexcican** [penibelst/jekyll-compress-html#90]
Hey, thanks for this plugin. It works great, aside from one small issue. I have a code that displays the `excerpt` of a blog post in the `<description>` metatag of the website:
```
<meta name="description" content="{% if page.layout == 'default' %}{{ site.description }}{% else %}{% if page.categories %}{{ content | split:'<!--more-->' | first | strip_html }}{% endif %}{% endif %}" />
```

Which is basically saying if the page has categories (blog post) show in the description the `excerpt` without any `html` tags. If not, show the default site description.

This works fine for blog posts, but for normal pages, it doesn’t bring the description, and it’s just blank:
```
<meta name="description" content="" />
```

Any ideas?

**Comment by kleinfreund** [comment]
The split part of your Liquid snippet will be empty after compress.html runs since it is an HTML comment. Hence the result will be empty, too. 

Not an issue of the compress layout.

**Comment by alexcican** [comment]
I tried removing:
```
comments: ["<!-- ", " -->"]
```
from the `config.yml`, and it had no result.

**Comment by alexcican** [comment]
Also, the weird thing is that the second part (`{% else %}`) is not empty—it displays the `content | split:'<!--more-->' | first | strip_html` fine. 

It’s the first part of the Liquid snippet which gets emptied for some reason…
```
{% if page.layout == 'default' %}{{ site.description }}
```

**Comment by kleinfreund** [comment]
This is indeed weird, but I’m still not convinced that this is an issue of the compress.html layout.

**Comment by alexcican** [comment]
I think it is an issue, because I pin-pointed it a bit. If I do this:
```
<meta name="description" content="{% if page.layout == 'default' %}{{ site.description }}{% endif %}" />
```
It doesn’t show the description. But if I remove the `==`:
```
<meta name="description" content="{% if page.layout %}{{ site.description }}{% endif %}" />
```
It shows the description. Weird…

**Comment by kleinfreund** [comment]
Can you output `{{ page.layout }}` instead of `{{ site.description }}` in the latter example and examine on which pages it is as expected and where maybe not?

**Comment by jnvsor** [comment]
> The split part of your Liquid snippet will be empty after compress.html runs since it is an HTML comment.

It's been a while since I did any work on JCH but I'm pretty sure that's not true - the subtemplates render first and pure html is what gets passed to compress.

What I gather from this thread is that it's an issue with your `page.layout` in the if, though I'd like to point out you may run into problems regardless of compress if you don't escape the HTML you're putting into the attributes.

Most likely your pages don't actually have a layout at all by default - does it work with something like `page.layout | default: "default" == "default"`?

**Comment by alexcican** [comment]
@jnvsor it does have a `layout.html`

> though I'd like to point out you may run into problems regardless of compress if you don't escape the HTML you're putting into the attributes.

Then how do you explain the fact that when I disable `compress.html` it shows the `{{ site.description }}` just fine, escaped and all… It obviously has something to do with compress and `{{ page.layout }}`.

Anyway, the way I solved it was like this:
```
<meta property="description" content="{% if page.categories == nil %}{{ site.description }}{% else if page.categories %}{{ content | split:'<!--more-->' | first | strip_html }}{% endif %}" />
