### ISSUE TITLE
Losing page title on compression

### ISSUE THREAD

**Issue by sajal2692** [penibelst/jekyll-compress-html#92]
Hi there. 

I've noticed that I lose the title for pages when I use the compress layout. The "Pages" are usually markdown files, with titles i YAML front matter.  But the same happens for .html files with their titles in YAML front matter too.

Not sure what's going on, or if it's even an issue with compress.

**Comment by jnvsor** [comment]
Are you talking about `<title>` titles or `<h1>` titles? What are your templates like? What's your output like? Got a source code example?

**Comment by sajal2692** [comment]
Thanks for the quick reply, and apologies for the vague initial question.

Talking about the <title> tag, but just discovered that using compress also eats up a <meta> tag I had in my head.html _include file that enabled responsiveness. So the problem's just there in the  I think. 

Snippet from my head.html file:

```
<head>
  <link href="http://gmpg.org/xfn/11" rel="profile">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta http-equiv="content-type" content="text/html; charset=utf-8">

  <!-- Enable responsiveness on mobile devices-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">

  <title>
    {% if page.title == "Home" %}
      {{ site.title }} &middot; {{ site.tagline }}
    {% else %}
      {{ page.title }} &middot; {{ site.title }}
    {% endif %}
  </title>
...
...
```

And snippet from my default-home.html 

```
---
layout: compress
---

<!DOCTYPE html>
<html lang="en-us">

  {% include head.html %}

  <body>

    {% include sidebar.html %}
```

Output:

`<!DOCTYPE html> <html lang="en-us"> <head> <link href="http://gmpg.org/xfn/11" rel="profile"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta http-equiv="content-type" content="text/html; charset=utf-8"> <script> ..google analytics script..`

My repo's located at https://github.com/sajal2692/sajal2692.github.io 
Source's the default branch where you can find said layouts. Master branch's where the site gets published, so you can find the said output at index.html in that branch.

Hope this helps. In the meantime I'm going to do some more investigating.

**Comment by sajal2692** [comment]
Ok, so I figured it out. 

In my _config.yml, I had specified 

```
compress_html:
  comments: ["<!-- ", " -->"]
```
Because I wanted to remove the comments.

So this line:
`<!-- Enable responsiveness on mobile devices-->` 
caused the behaviour as there a missing whitespace before closing the comment.

I copy pasted it from the docs. I'm wondering if the whitespace is needed there? Or does `comments: ["<!--", "-->"]` cover all use cases. Minor nag, though.

**Comment by jnvsor** [comment]
The whitespace is there so that we don't eat conditional comments. You know, the `<!--[if lte IE 7]>...` things to hack around old IE versions. If you don't use them you can remove the whitespace from the comments in the config for no ill effect
