### ISSUE TITLE
Can JCH compress the html to one line ? How can I remove the comments in the inline js and the comments in the html at the same time ?

### ISSUE THREAD

**Issue by qytang326** [penibelst/jekyll-compress-html#95]
I see the warning, but I still want to raise this issue, because I think they may be solved if you want to rewrite the `site.compress_html.comments` to let it support an array divided by a semicolon to present different types of comments. Then I have two questions.
1.  Which configuration should I take if I want to compress the htmls within one line ?
2. How can I remove the comments in the inline js like `/* comments */` and the comments in the htmls like `<!-- comments -->` at the same time? Now I choose a stupid solution: run the JCH twice which the different configurations.... Is there a more smart solution?

**Comment by jnvsor** [comment]
> I think they may be solved if you want to rewrite the `site.compress_html.comments` to let it support an array divided by a semicolon to present different types of comments

Good luck with that! (Seriously yikes, not possible in liquid)

> Which configuration should I take if I want to compress the htmls within one line ?

The default will do that except for script/style/pre tags where whitespace has meaning.

> How can I remove the comments in the inline js like `/* comments */` and the comments in the htmls like `<!-- comments -->` at the same time? Now I choose a stupid solution: run the JCH twice which the different configurations.... Is there a more smart solution?

Use a separate compression program written in a real language. Jekyll plugin or separate build system. Liquid is very limited and this should only really be used on github pages where you can't use plugins. Plus you'll get proper JS compression and the like.

Running it twice with different configs will work, unless you have a literal `/* text */` in your html or vice-versa, then it won't...
