### ISSUE TITLE
Paragraph ending tag </p> is removed inappropriate

### ISSUE THREAD

**Issue by laukstein** [penibelst/jekyll-compress-html#96]
Here HTML having `layout: compress`:

```
<p>Text</p>
<a href>Link</a>
```

it is wrongly converted to

```
<p>Text <a href>Link</a>
```

that browser will understand as 

```
<p>Text <a href>Link</a></p>
```

The **expected result** here is

```
<p>Text</p><a href>Link</a>
```

`</p>` is one of the optional ending tags (could be dropped and stil have valid HTML). But when dropped in inappropriate place, it can break the whole layout. The same for `</li>`, `</ol>`, etc.

**Comment by jnvsor** [comment]
I see. I'll remove it from the default ending tags list tonight. Thanks!

**Comment by jnvsor** [comment]
Looks like most of the ending tags are inside containers of some sort that do require ending tags (`<table>`, `<ul>`, etc) so fixed in 00a5b737392f11ffb7dd61aef626827424b4564a

**Comment by laukstein** [comment]
@jnvsor, perhaps [_layouts/compress.html](https://github.com/penibelst/jekyll-compress-html/blob/master/site/_layouts/compress.html) needs to be updated too? Can you update it?

**Comment by jnvsor** [comment]
Well that was stupid. I forgot I have to manually upload the built file to the tag when it's done. Now available for download on [the tag page](https://github.com/penibelst/jekyll-compress-html/releases/tag/v3.0.4)
